import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <nav className="bg-slate-900 text-slate-100 text-sm px-6 py-3 flex gap-5 items-center shadow">
            <a className="font-semibold tracking-wide" href="/">
              Dashboard
            </a>
            <a href="/accounts" className="hover:underline">
              Accounts
            </a>
            <a href="/outbound" className="hover:underline">
              Outbound
            </a>
            <a href="/outbound-metrics" className="hover:underline">
              Touch Metrics
            </a>
            <a href="/charts" className="hover:underline">
              Charts
            </a>
          </nav>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
